// GENERATED by scripts/encode-stills.sh — do not edit by hand.
//
// Real pixel dimensions for each supporting still, so layout can reserve the
// correct box per image rather than assuming one aspect ratio per project.

export interface StillMeta {
  file: string;
  width: number;
  height: number;
}

export const stillsManifest: Record<string, StillMeta[]> = {
  "blaque-diamond-model-s": [
    { file: "01.d33c42e4.jpg", width: 2560, height: 1706 },
    { file: "02.cdca932c.jpg", width: 2560, height: 1706 },
    { file: "03.f2cfef96.jpg", width: 2560, height: 1706 },
    { file: "04.25ba6d72.jpg", width: 2560, height: 1706 },
    { file: "05.5a787fc9.jpg", width: 2560, height: 1706 },
    { file: "06.3dfe8a91.jpg", width: 2560, height: 1706 },
  ],
  "blazar-mantis-135": [
    { file: "01.3ea38af6.jpg", width: 1706, height: 2560 },
    { file: "02.92edccec.jpg", width: 1706, height: 2560 },
    { file: "03.0fc3a92e.jpg", width: 2560, height: 1706 },
    { file: "04.ff5b7c18.jpg", width: 2560, height: 1706 },
    { file: "05.92361b0b.jpg", width: 1706, height: 2560 },
  ],
  "fd-2022-buy-now-japan": [
    { file: "01.4e9022b8.jpg", width: 2560, height: 1706 },
    { file: "02.1b46926b.jpg", width: 2560, height: 1706 },
    { file: "03.8d331f21.jpg", width: 2560, height: 1706 },
    { file: "04.5ddc3872.jpg", width: 2560, height: 1706 },
    { file: "05.3ea0e527.jpg", width: 2560, height: 1706 },
    { file: "06.5cc17aaa.jpg", width: 2560, height: 1706 },
  ],
  "shoreline-f150-raptor": [
    { file: "01.9dc87aee.jpg", width: 2560, height: 1706 },
    { file: "02.ca093864.jpg", width: 2560, height: 1706 },
    { file: "03.85fcf7de.jpg", width: 2560, height: 1706 },
    { file: "04.9a5cc160.jpg", width: 2560, height: 1706 },
    { file: "05.02e3b562.jpg", width: 2560, height: 1706 },
    { file: "06.7b416446.jpg", width: 2560, height: 1706 },
  ],
};
