// GENERATED by scripts/encode-stills.sh — do not edit by hand.
//
// Real pixel dimensions for each supporting still, so layout can reserve the
// correct box per image rather than assuming one aspect ratio per project.

export interface StillMeta {
  file: string;
  width: number;
  height: number;
}

export const stillsManifest: Record<string, StillMeta[]> = {
  "blaque-diamond-model-s": [
    { file: "01.jpg", width: 1600, height: 1066 },
    { file: "02.jpg", width: 1600, height: 1066 },
    { file: "03.jpg", width: 1600, height: 1066 },
    { file: "04.jpg", width: 1600, height: 1066 },
    { file: "05.jpg", width: 1600, height: 1066 },
    { file: "06.jpg", width: 1600, height: 1066 },
  ],
  "blazar-mantis-135": [
    { file: "01.jpg", width: 1066, height: 1600 },
    { file: "02.jpg", width: 1066, height: 1600 },
    { file: "03.jpg", width: 1600, height: 1066 },
    { file: "04.jpg", width: 1600, height: 1066 },
    { file: "05.jpg", width: 1066, height: 1600 },
  ],
  "fd-2022-buy-now-japan": [
    { file: "01.jpg", width: 1600, height: 1066 },
    { file: "02.jpg", width: 1600, height: 1066 },
    { file: "03.jpg", width: 1600, height: 1066 },
    { file: "04.jpg", width: 1600, height: 1066 },
    { file: "05.jpg", width: 1600, height: 1066 },
    { file: "06.jpg", width: 1600, height: 1066 },
  ],
  "joby-joshua-tree": [
    { file: "01.jpg", width: 1600, height: 900 },
    { file: "02.jpg", width: 1066, height: 1600 },
    { file: "03.jpg", width: 1600, height: 1066 },
    { file: "04.jpg", width: 1600, height: 1066 },
    { file: "05.jpg", width: 1600, height: 1066 },
    { file: "06.jpg", width: 1600, height: 1066 },
  ],
  "shoreline-f150-raptor": [
    { file: "01.jpg", width: 1600, height: 1066 },
    { file: "02.jpg", width: 1600, height: 1066 },
    { file: "03.jpg", width: 1600, height: 1066 },
    { file: "04.jpg", width: 1600, height: 1066 },
    { file: "05.jpg", width: 1600, height: 1066 },
    { file: "06.jpg", width: 1600, height: 1066 },
  ],
};
